### ISSUE TITLE
Fix endianness for height in confirmation_height table

### ISSUE THREAD

**Issue by mistakia** [nanocurrency/nanodb-specification#11]
I'm opening this issue for posterity (as things get lost on discord) and to document any outdated or incorrect specs before following up with a draft PR.

https://github.com/nanocurrency/nanodb-specification/blob/68e5c0029c98edba5da7722571e9b1b265b54e14/nanodb.ksy#L58-L61

The height endianness needs to be updated to little endian. 

Edit: After going through the spec using the generated parser on an lmdb file, the results matched the outputs from a public node's rpc except for the confirmation height value.

**Comment by cryptocode** [comment]
Thanks for catching this and verifying the rest, much appreciated!
